- hosts: all
  become: true
  roles:
   - role: commons

- hosts: red_interna
  become: true
  roles:
   - role: red_interna

- hosts: router
  become: true
  roles:
   - role: router

- hosts: web
  become: true
  roles:
   - role: web

- hosts: bd
  become: true
  roles:
   - role: mariadb
